### ISSUE TITLE
接口权限扫描在哪里控制?

### ISSUE THREAD

**Issue by gitkmw** [CaiBaoHong/biu#1]
接口的权限元数据是定义在server/com/abc/controller目录下的各种Controller中的,这个是在哪里控制的?如果我要建server/com/abc/controller/order/OrderController,如果扫描到?

**Comment by CaiBaoHong** [comment]
默认就会扫描到的，pval默认值取的是@RequestMapping的值，pname取的值是Controller的类名。你也可以使用@PermInfo加上自定义的pname，pval信息。TestController可以看到示例。

**Comment by CaiBaoHong** [comment]
刚才看漏了，是因为你加多了一层包名‘order’，而我的包名判断逻辑直接用的是equals。所以你自己改改就好。在SysPermController的“/meta/api”接口，把beans.stream().filter(b -> StringUtils.equals(basicPackage, ClassUtils.getPackageName(b.getClass())))，改成：beans.stream().filter(b -> StringUtils.startsWith(ClassUtils.getPackageName(b.getClass()),basicPackage))

**Comment by gitkmw** [comment]
非常感谢! 建议作者弄个文档,建个qq群,这样大家都可以为这个项目贡献点什么.
