### ISSUE TITLE
是否可以提供一个可以看demo的连接呢？

### ISSUE THREAD

**Issue by guanrongYang** [CaiBaoHong/biu#2]
我对您这个项目有点兴趣，但我只想看下运行之后的效果以及浏览代码的一些关键部分。不知您是否有部署一个demo的兴趣呢？

**Comment by CaiBaoHong** [comment]
你好，情况有点尴尬。1.目前我还在写第2版，写好后这个版本就没啥意义了；2.我没闲钱买服务器。见谅~~~

**Comment by CaiBaoHong** [comment]
写好第2版后我会考虑完善文档并部署一个demo的。见谅~~~

**Comment by guanrongYang** [comment]
希望越来越好。  

我自己配置看下好了，虽然需要花费点时间。哈哈。
